server:
  port: 8081
  servlet:
    context-path: /resource


logging:
  level:
    org:
      springframework:
        security: DEBUG
spring:
  jpa:
    # Driver Class = org.h2.Driver
    # JDBC URL = jdbc:h2:mem:testdb
    database-platform: H2
    show-sql: TRUE
    hibernate:
      ddl-auto: 'create-drop'

spring.h2.console:
  enabled: true
  path: /h2-console

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8082/auth/oauth/check_token